name = "LindbladVectorizedTensors"
uuid = "6455c26f-8985-4381-925b-8a93509e9dbd"
authors = ["Davide Ferracin <davide.ferracin@protonmail.com> and contributors"]
version = "0.13.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ITensors = "0.3.19"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
