name = "LindbladVectorizedTensors"
uuid = "6455c26f-8985-4381-925b-8a93509e9dbd"
authors = ["Davide Ferracin <davide.ferracin@protonmail.com> and contributors"]
version = "0.0.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
